import type { Student, Event } from "./types"

export const students: Student[] = [
  {
    id: 1001,
    name: "Alex Johnson",
    email: "alex.j@university.edu",
    eventName: "Hackathon 2025",
    registrationDate: "2025-01-15",
    isPaid: true,
    paymentMethod: "Credit Card",
  },
  {
    id: 1002,
    name: "Samantha Lee",
    email: "sam.lee@university.edu",
    eventName: "AI Workshop",
    registrationDate: "2025-01-18",
    isPaid: true,
    paymentMethod: "PayPal",
  },
  {
    id: 1003,
    name: "Michael Chen",
    email: "m.chen@university.edu",
    eventName: "Web Dev Conference",
    registrationDate: "2025-01-20",
    isPaid: false,
  },
  {
    id: 1004,
    name: "Jessica Taylor",
    email: "j.taylor@university.edu",
    eventName: "Hackathon 2025",
    registrationDate: "2025-01-22",
    isPaid: true,
    paymentMethod: "Bank Transfer",
  },
  {
    id: 1005,
    name: "David Wilson",
    email: "d.wilson@university.edu",
    eventName: "Cybersecurity Summit",
    registrationDate: "2025-01-25",
    isPaid: false,
  },
  {
    id: 1006,
    name: "Emily Rodriguez",
    email: "e.rodriguez@university.edu",
    eventName: "AI Workshop",
    registrationDate: "2025-01-27",
    isPaid: true,
    paymentMethod: "Credit Card",
  },
  {
    id: 1007,
    name: "James Martin",
    email: "j.martin@university.edu",
    eventName: "Web Dev Conference",
    registrationDate: "2025-01-28",
    isPaid: true,
    paymentMethod: "PayPal",
  },
  {
    id: 1008,
    name: "Sophia Garcia",
    email: "s.garcia@university.edu",
    eventName: "Cybersecurity Summit",
    registrationDate: "2025-01-30",
    isPaid: false,
  },
  {
    id: 1009,
    name: "Daniel Brown",
    email: "d.brown@university.edu",
    eventName: "Hackathon 2025",
    registrationDate: "2025-02-01",
    isPaid: true,
    paymentMethod: "Bank Transfer",
  },
  {
    id: 1010,
    name: "Olivia Thompson",
    email: "o.thompson@university.edu",
    eventName: "AI Workshop",
    registrationDate: "2025-02-03",
    isPaid: false,
  },
  {
    id: 1011,
    name: "Ethan Davis",
    email: "e.davis@university.edu",
    eventName: "Web Dev Conference",
    registrationDate: "2025-02-05",
    isPaid: true,
    paymentMethod: "Credit Card",
  },
  {
    id: 1012,
    name: "Ava Martinez",
    email: "a.martinez@university.edu",
    eventName: "Cybersecurity Summit",
    registrationDate: "2025-02-07",
    isPaid: true,
    paymentMethod: "PayPal",
  },
]

export const events: Event[] = [
  {
    id: 1,
    name: "Hackathon 2025",
    date: "2025-03-15",
    registrationCount: 120,
  },
  {
    id: 2,
    name: "AI Workshop",
    date: "2025-04-10",
    registrationCount: 85,
  },
  {
    id: 3,
    name: "Web Dev Conference",
    date: "2025-05-22",
    registrationCount: 95,
  },
  {
    id: 4,
    name: "Cybersecurity Summit",
    date: "2025-06-18",
    registrationCount: 70,
  },
]

